### ISSUE TITLE
Add "review-requested" filter

### ISSUE THREAD

**Issue by k** [ohbarye/review-waiting-list-bot#32]
It would be nice to be able to run a command that would allow one to filter based on reviewer-requested so reminders could be sent to specific slack users about PR reviews that need to be done

**Comment by ohbarye** [comment]
Thanks for your feedback. 

I first thought that it's not a tough work, but I found GitHub's search API doesn't return `requested_reviewers` information.
https://developer.github.com/v3/search/

Please give me some time to consider how to implement it.

**Comment by k** [comment]
ah yeah thats a bummer :( 

looks like for each PR this request will have to be made: https://developer.github.com/v3/pulls/review_requests/

**Comment by ohbarye** [comment]
Hello @k 
In order to pull through the N+1 problem, I changed this bot to use GraphQL. Then I added an implementation to support `reviewer` as a filter by https://github.com/ohbarye/review-waiting-list-bot/pull/37.

I hope this change would make your development life happier.

**Comment by k** [comment]
Wow thanks! I’ll give it a spin. :)

**Comment by k** [comment]
I ran into an issue. So i launched the docker file with:

`FROM ohbarye/review-waiting-list-bot:support-requested-reviewers`

at the top, but I get an error in from server:

```
node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'members' of undefined
    at GitHubApiClient.getTeamMembers (/usr/src/app/src/GitHubApiClient.js:137:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by ohbarye** [comment]
@k 
No, I haven't. But I guess it would happen when you give a team name that is not existent like below.

```
@review-bot ls author:org/nil
```

Then `team` would be `undefined` [here](https://github.com/ohbarye/review-waiting-list-bot/blob/7ad720f730ead021a914726b6963c727098f0968/src/GitHubApiClient.js#L140) and such an error would be raised.

**Comment by ohbarye** [comment]
Yeah, my guesss may be right because I could reproduce the error.
Let me open another issue and try to fix.

**Comment by k** [comment]
Great I think i narrowed down the problem. The reviewer feature is working great for user authors, thanks! 

Now it doesn't throw the error, but I think the new graphql API is having trouble finding my org/team. Before when I would do `@review-bot ls author:org/team-that-exists` it would list all the prs but now it doesn't. I tried a different team I had permissions too and it still didn't work.

**Comment by ohbarye** [comment]
@k 
> Before when I would do @review-bot ls author:org/team-that-exists it would list all the prs but now it doesn't. I tried a different team I had permissions too and it still didn't work.

For the problem, could you check if your access token has permission for `read:org` & `read:discussion`? GitHub graphql API seems to have another permission policy a bit different from the former one.
ref: https://github.com/ohbarye/review-waiting-list-bot#note-about-scopes-of-github_auth_token

**Comment by k** [comment]
@ohbarye yeah I think the permissions were set up properly. This is the setup for the token I was using:
![image](https://user-images.githubusercontent.com/2452636/40152304-bc66e6ba-5939-11e8-826e-74da9f375577.png)

**Comment by ohbarye** [comment]
@k 
Could you give me further info, does your problem match https://github.com/ohbarye/review-waiting-list-bot/issues/46?
In other words, does your command to the bot include double quotations (`""`)?

**Comment by ohbarye** [comment]
@k 
I found a pagination issue and I guess your problem is related to it. I'll fix it in https://github.com/ohbarye/review-waiting-list-bot/issues/48, so please give me some time. 🙇

**Comment by k** [comment]
Ah I see. No rush 🙂
