### ISSUE TITLE
Botkit Studio statistics are no longer supported

### ISSUE THREAD

**Issue by k-hashimoto** [ohbarye/review-waiting-list-bot#55]
Hi,

Latest version of review-waiting-list-bot was deployed to Heroku and run slack-bot like,

`@review-waiting-list-dev ls reviewer:GITHUB_USERNAME`

I have no message on slack. But I got following error message on Heroku console.

`
2019-01-22T08:13:37.917316+00:00 app[worker.1]: Botkit Studio statistics are no longer supported. Update your project to the latest version of Botkit, or add `stats_optout: true` to your bot configuration.
2019-01-22T08:13:38.235446+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined
2019-01-22T08:13:38.235458+00:00 app[worker.1]:     at GitHubApiClient.getPullRequestsForAuthors (/app/src/GitHubApiClient.js:99:38)
2019-01-22T08:13:38.235460+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/next_tick.js:81:5)
2019-01-22T08:13:38.235507+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
`

**Comment by k-hashimoto** [comment]
I checked your code on [github.](https://github.com/ohbarye/review-waiting-list-bot/blob/master/src/GitHubApiClient.js  ) 

`GitHubApiClient.getPullRequestsForAuthors` `(/app/src/GitHubApiClient.js:99:38)`

Maybe, axios could get response from github, but could not extract data from response.

**Comment by ohbarye** [comment]
Thanks for reporting!

I had a look at this, and updated code to suppress the warning at https://github.com/ohbarye/review-waiting-list-bot/pull/56.

But I'm thinking that the message about `Botkit Studio statistics` is not an essential problem. Because I was able to reproduce the message before #56, but the bot correctly posted messages to my Slack.

**Comment by k-hashimoto** [comment]
Thank you for your quick response! So is type error not problem?

`(node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined`

**Comment by ohbarye** [comment]
Well, the type error is the real problem, which is not related to `Botkit Studio statistics`. I couldn't reproduce the type error.

**Comment by k-hashimoto** [comment]
Hi,

I checked  slack bot and github settings and  scope of GITHUB_AUTH_TOKEN  was wrong.  I'm sorry for waisting your time.

**Comment by ohbarye** [comment]
@k-hashimoto 
No worries. Thanks for using my bot!
